### ISSUE TITLE
Installation task error

### ISSUE THREAD

**Issue by pantoniotti** [spree-contrib/spree_address_book#99]
I am running spree 3-1-0 (have to)
in Gemfile:
gem 'spree_address_book', github: 'spree-contrib/spree_address_book', branch: 'master'

Running:
bundle exec rails g spree_address_book:install
I get the following error:

/Users/pantoniotti/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:98:in `binread': No such file or directory @ rb_sysopen - /Users/pantoniotti/O2Web/Sources/skedio_site/vendor/assets/javascripts/spree/frontend/all.js (Errno::ENOENT)
        from /Users/pantoniotti/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:98:in `replace!'

**Comment by pantoniotti** [comment]
Seems your script only supports all.js and I have all.js.coffee.
Creating all.js manually fixes the issue
